---
title: "FB & INSTAGRAM POLITICAL ADS"
author: "Ondrej Pekacek/TI CZ"
date: "Last updated `r format (Sys.time(),'%d. %m. %Y')`"
output: 
  flexdashboard::flex_dashboard:
    logo: "data/logo_ti.png"
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/opop999/election_monitoring_fb_ads
    navbar:
      - {title: "About", icon: "ion-information-circled", href: "https://www.transparentnivolby.cz/snemovna2021"}
---

```{r setup, include=FALSE}
# Disable scientific notation of numbers
options(scipen = 999)

# Package names
packages <- c("flexdashboard", "dplyr", "ggplot2", "plotly", "forcats", "htmlwidgets", "tidyr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

summary_dataset <- readRDS(file = "data/summary_tables/merged_summary.rds")
time_dataset <- readRDS(file = "data/summary_tables/time_summary.rds")

# Specify output directory for individual html plots (to be embedded to website)
directory <- "data/html_plots"

# Check whether output directory exists to save individual plots
if (!dir.exists(directory)) {
  dir.create(directory)
} else {
  print("Output directory already exists")
}

# Select TOP 10 biggest spenders for plotting
top_10_spenders <- summary_dataset %>%
  slice_max(avg_spend, n = 10) %>%
  select(page_name, page_id, avg_spend)

```

Total Ads
=====================================

Column
-----------------------------------------------------------------------

### Total Ads

```{r}
plot_total_ads <- ggplotly(summary_dataset %>%
  filter(total_ads > 10) %>%
  ggplot(aes(x = total_ads, y = reorder(page_name, total_ads), fill = percent_unique)) +
  geom_col() +
  scale_fill_gradient(
    low = "#fbe8e7", high = "#db1d0b",
    limits = c(0, 1),
    breaks = c(0, 0.25, 0.50, 0.75, 1),
    labels = c("0%", "25%", "50%", "75%", "100%")
  ) +
  scale_x_continuous(
    breaks = seq(0, 2500, 250),
    labels = seq(0, 2500, 250)
  ) +
  theme_minimal() +
  xlab("Total Ads") +
  ylab(element_blank()) +
  labs(fill = "Proportion unique ads") +
  ggtitle("Ads since 1.1.2021 of pages with more than 10 ads"))

plot_total_ads

htmlwidgets::saveWidget(plot_total_ads, file = paste0(directory, "/plot_total_ads.html"))

```

Total Spending
=====================================

Column 
-----------------------------------------------------------------------

### Total Spending 

```{r}
plot_total_spending <- ggplotly(summary_dataset %>%
  filter(total_ads > 10) %>%
  mutate(
    avg_spend_1000 = round(avg_spend / 1000, digits = 0),
    per_ad_avg_spend_1000 = round(per_ad_avg_spend / 1000, digits = 1)
  ) %>%
  ggplot(aes(x = avg_spend_1000, y = reorder(page_name, avg_spend), fill = per_ad_avg_spend_1000)) +
  geom_col() +
  scale_fill_gradient2(
    low = "#cddae5", 
    mid = "#03457f",
    high = "#023766",
    midpoint = 12,
    limits = c(0, 25)
  ) +
  scale_x_continuous(breaks = seq(0, 3000, 250),
                    labels = seq(0, 3000, 250)) +
  theme_minimal() +
  xlab("Total Spend (CZK thousands)") +
  ylab(element_blank()) +
  labs(fill = "Per Ad (CZK thousands)") +
  ggtitle("Spending on ads since 1.1.2021"))

plot_total_spending

htmlwidgets::saveWidget(plot_total_spending, file = paste0(directory, "/plot_total_spending.html"))

```

Ad Runtime
=====================================

Column 
-----------------------------------------------------------------------

### Ad Runtime 

```{r}
plot_total_spending <- ggplotly(summary_dataset %>%
  filter(total_ads > 10) %>%
  ggplot(aes(x = avg_ad_runtime, y = reorder(page_name, avg_ad_runtime))) +
  geom_col(fill = "#026663") +
  scale_x_continuous(breaks = seq(0, 30, 2),
                    labels = seq(0, 30, 2)) +
  theme_minimal() +
  xlab("Days") +
  ylab(element_blank()) +
  ggtitle("Average Ad runtime since 1.1.2021"))

plot_total_spending

htmlwidgets::saveWidget(plot_total_spending, file = paste0(directory, "/plot_total_spending.html"))

```


Total Impressions
=====================================

Column 
-----------------------------------------------------------------------

### Total Impressions (square root scale)

```{r}
plot_total_impressions <- ggplotly(summary_dataset %>%
  filter(total_ads > 10) %>%
  mutate(
    avg_impressions_million = round(total_avg_impressions / 1000000, digits = 3),
    per_ad_avg_impressions_1000 = round(per_ad_avg_impression / 1000, digits = 1)
  ) %>%
  ggplot(aes(x = avg_impressions_million, y = reorder(page_name, avg_impressions_million), fill = per_ad_avg_impressions_1000)) +
  geom_col() +
  scale_fill_gradient2(
    low = "#e7fbe8",
    mid = "#089914",
    high = "#011603",
    midpoint = 200,
    limits = c(0, 400)
  ) +
  scale_x_sqrt(breaks = seq(0, 100, 10),
                    labels = seq(0, 100, 10)) +
  theme_minimal() +
  xlab("Total Impressions (millions)") +
  ylab(element_blank()) +
  labs(fill = "Per Ad impressions (thousands)") +
  ggtitle("Total impression of political ads since 1.1.2021, square root scale"))

plot_total_impressions

htmlwidgets::saveWidget(plot_total_impressions, file = paste0(directory, "/plot_total_impressions.html"))

```


Total Reach (minimal)
=====================================

Column 
-----------------------------------------------------------------------

### Total Reach (minimal, square root scale)

```{r}
plot_total_reach <- ggplotly(summary_dataset %>%
  filter(total_ads > 10) %>%
  mutate(
    avg_min_reach_million = round(total_min_reach / 1000000, digits = 2),
    per_ad_avg_min_reach_1000 = round(per_ad_min_reach / 1000, digits = 0)
  ) %>%
  ggplot(aes(x = avg_min_reach_million, y = reorder(page_name, avg_min_reach_million), fill = per_ad_avg_min_reach_1000)) +
  geom_col() +
  scale_fill_gradient2(
    low = "#f0e6eb",
    mid = "#660237",
    high = "#14000b",
    midpoint = 500,
    limits = c(0, 1000)
  ) +
  scale_x_sqrt(breaks = seq(0, 5000, 250),
                     labels = seq(0, 5000, 250)) +
  theme_minimal() +
  xlab("Total reach (millions)") +
  ylab(element_blank()) +
  labs(fill = "Per Ad reach (thousands)") +
  ggtitle("Total (minimal) reach of political ads since 1.1.2021, square root scale"))

plot_total_reach

htmlwidgets::saveWidget(plot_total_reach, file = paste0(directory, "/plot_total_reach.html"))

```


Spending & Time
=====================================

Column 
-----------------------------------------------------------------------

### Spending in time (10 biggest spenders)

```{r}
spend_over_time <- ggplotly(
  time_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    mutate(
      ad_creation_time_week = as.Date(cut(ad_creation_time, breaks = "week", start.on.monday = TRUE)) + 4,
      cumulative_spend_million = round((cumulative_spend / 1000000), digits = 3)
    ) %>%
    group_by(page_name, ad_creation_time_week) %>% 
    summarise(end_of_week_million_spend = max(cumulative_spend_million)) %>% 
    ungroup() %>% 
    ggplot(aes(x = ad_creation_time_week, y = end_of_week_million_spend, color = page_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(as.Date("2021-10-08"))), color = "#db1d0b") +
    geom_text(aes(x = as.Date("2021-10-08"), y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 5, 0.5),
      labels = seq(0, 5, 0.5)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%m") +
    coord_cartesian(xlim = c(as.Date("2021-01-01"), as.Date("2021-11-05")), expand = TRUE) +
    theme(legend.title = element_blank()) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle("Spending (in millions CZK) on FB Ads, January 2021-present")
)

spend_over_time

htmlwidgets::saveWidget(spend_over_time, file = paste0(directory, "/spend_over_time.html"))

```

Gender
=====================================

Column 
-----------------------------------------------------------------------

### Ads by Gender

```{r}
plot_gender <- ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    ggplot(aes(x = avg_male, y = reorder(page_name, avg_male), fill = avg_male)) +
    geom_col() +
    geom_vline(aes(xintercept = 0.5, color = "#db0b50")) +
    scale_fill_gradient(
      low = "#db1d0b", high = "#03457f",
    ) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, 0.25),
      labels = c("0%", "25%", "50%", "75%", "100%")
    ) +
    theme_minimal() +
    theme(legend.position = "none") +
    xlab("Proportion Ads Targeting Male Audience") +
    ylab(element_blank()) +
    ggtitle("Proportion of Ads since 1.1.2021 targeting male users")
)

plot_gender

htmlwidgets::saveWidget(plot_gender, file = paste0(directory, "/plot_gender.html"))

```

Age
=====================================

Column 
-----------------------------------------------------------------------

### Ads by Age (10 biggest spenders)

```{r}
plot_age <- ggplotly(
  summary_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    select(
      page_name,
      avg_18_24,
      avg_25_34,
      avg_35_44,
      avg_45_54,
      avg_55_64,
      avg_65_plus
    ) %>%
    pivot_longer(cols = 2:7, names_to = "age_group", values_to = "proportion", values_drop_na = TRUE) %>%
    ggplot(aes(x = age_group, y = proportion, fill = page_name)) +
    geom_col(position = "dodge2") +
    scale_x_discrete(labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")) +
    scale_fill_brewer(palette = "Paired") +
    scale_y_continuous(
      limits = c(0, 0.5),
      breaks = seq(0, 0.5, 0.1),
      labels = c("0%", "10%", "20%", "30%", "40%", "50%")
    ) +
    theme_minimal() +
    theme(legend.title = element_blank()) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle("Proportion of Ads since 1.1.2021 targeting specific age groups")
)

plot_age

htmlwidgets::saveWidget(plot_age, file = paste0(directory, "/plot_age.html"))

```



Region
=====================================

Column 
-----------------------------------------------------------------------

### Ads by Region (10 biggest spenders)

```{r}
plot_region <- ggplotly(
  summary_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    select(
      page_name,
      avg_pha,
      avg_stc, 
      avg_jhc, 
      avg_plk, 
      avg_kvk, 
      avg_ulk, 
      avg_lbk, 
      avg_hkk,
      avg_pak,
      avg_vys,
      avg_jhm,
      avg_olk,
      avg_msk, 
      avg_zlk
    ) %>%
    pivot_longer(cols = 2:15, names_to = "region_group", values_to = "proportion", values_drop_na = TRUE) %>%
    ggplot(aes(x = region_group, y = proportion, fill = page_name)) +
    geom_col(position = "dodge2") +
   scale_x_discrete(labels = c("HKK", "JHC", "JHM", "KVK", "LBK", "MSK", "OLK", "PAK", "PHA", "PLK", "STC", "ULK", "VYS", "ZLK")) +
    scale_fill_brewer(palette = "Paired") +
    scale_y_continuous(
      limits = c(0, 0.5),
      breaks = seq(0, 0.5, 0.1),
      labels = c("0%", "10%", "20%", "30%", "40%", "50%")
    ) +
    theme_minimal() +
    theme(legend.title = element_blank()) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    ggtitle("Proportion of Ads since 1.1.2021 targeting specific age groups")
)

plot_region

htmlwidgets::saveWidget(plot_region, file = paste0(directory, "/plot_region.html"))

```

