# PART 1: LOAD THE REQUIRED LIBRARIES FOR THIS SCRIPT

# Package names
packages <- c("httr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
	install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# PART 2: QUERY FB API, EXCHANGE SHORT TERM ACCESS TOKEN FOR BEARER TOKEN (2 MONTHS VALIDITY)

response <- httr::VERB(
	verb = "GET",
	url = "https://graph.facebook.com/v12.0/oauth/access_token",
	encode = "json",
	query = list(
		grant_type = "fb_exchange_token",
		client_id = Sys.getenv("FB_APP_ID"), # Enter Your APP ID.
		client_secret = Sys.getenv("FB_APP_SECRET"), # Enter Your Client Secret.
		fb_exchange_token = "ENTER-ACCESS-TOKEN" # Enter your short-term access token generated by FB login.
	)
)


# PART 3: CHECK API CALL RESPONSE FOR VALIDITY

if (http_error(response) == TRUE) {

	stop(paste0("API call for FB bearer token returned the following error: ",
							http_status(response)[["message"]],
							". Input parameters are likely invalid."))

}	else if (http_error(response) == FALSE) {

	print(paste0("Http status is: ",
							 http_status(response)[["message"]] ,
							 ". Attempting to retrieve token information"))

}


# PART 4: RETRIEVE TOKEN INFORMATION

response_content <- content(response, as = "parsed")

writeLines(c("The bearer token is:\n",
						 response_content$access_token,
						 "\nThe token expires on:\n",
						 as.character(as.Date(Sys.time() + response_content$expires_in))))

